ClickType               : BenchmarkAverageMaxCpc BenchmarkCtr SearchClickShare SearchImpressionShare
Device                  : BenchmarkAverageMaxCpc BenchmarkCtr
BenchmarkAverageMaxCpc  : ClickType Device
BenchmarkCtr            : ClickType Device
SearchImpressionShare   : ClickType
SearchClickShare        : ClickType
