ClickType               : AllConversionRate AllConversionValue AllConversions BenchmarkAverageMaxCpc BenchmarkCtr CostPerAllConversion CrossDeviceConversions SearchClickShare SearchImpressionShare ValuePerAllConversion
Device                  : BenchmarkAverageMaxCpc BenchmarkCtr
BenchmarkAverageMaxCpc  : ClickType Device
BenchmarkCtr            : ClickType Device
CrossDeviceConversions  : ClickType
CostPerAllConversion    : ClickType
SearchImpressionShare   : ClickType
SearchClickShare        : ClickType
ValuePerAllConversion   : ClickType
AllConversionValue      : ClickType
AllConversions          : ClickType
AllConversionRate       : ClickType
